version: '2'
services:
    drupal8:
        image: ngako/drupal8
        volumes:
            - "./app:/home/dev/app"
        environment:
            LOCAL_USER_NAME: ${USER}
            LOCAL_USER_ID: ${USER_ID}
        restart: always
        depends_on:
            - db
        links:
            - db:mysql
        ports:
            - "8080:80"
        container_name: drupal8-app
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: drupal8
            MYSQL_USER: drupal8
            MYSQL_USER_PASSWORD: drupal8
            
        
        
        
        
